name: Build Typst document
on:
  push:
    tags:
      - '*'
permissions:
  contents: write

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - run: typst compile cv.typ --font-path fonts

      - run: typst compile cv-tr.typ --font-path fonts

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: '*.pdf'

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2.0.5
        if: github.ref_type == 'tag'
        with:
          name: "${{ env.DATE }}"
          files: |
            cv.pdf
            cv-tr.pdf